# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'five.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setFixedSize(800, 600)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"border-image: url(:/beijing1/icons/four.png);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setStyleSheet("border-image: url(:/beijing1/icons/back.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, 180, 581, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.id1 = QtWidgets.QLabel(self.frame)
        self.id1.setGeometry(QtCore.QRect(160, 0, 91, 51))
        self.id1.setStyleSheet("font: 12pt \"Arial\";\n"
"")
        self.id1.setObjectName("id1")
        self.rank1 = QtWidgets.QLabel(self.frame)
        self.rank1.setGeometry(QtCore.QRect(20, 0, 91, 51))
        self.rank1.setStyleSheet("font: 12pt \"Arial\";")
        self.rank1.setObjectName("rank1")
        self.name1 = QtWidgets.QLabel(self.frame)
        self.name1.setGeometry(QtCore.QRect(300, 0, 181, 51))
        self.name1.setStyleSheet("font: 12pt \"Arial\";")
        self.name1.setObjectName("name1")
        self.point1 = QtWidgets.QLabel(self.frame)
        self.point1.setGeometry(QtCore.QRect(490, 0, 131, 51))
        self.point1.setStyleSheet("font: 12pt \"Arial\";")
        self.point1.setObjectName("point1")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(110, 230, 581, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.id2 = QtWidgets.QLabel(self.frame_2)
        self.id2.setGeometry(QtCore.QRect(160, 0, 91, 51))
        self.id2.setStyleSheet("font: 12pt \"Arial\";")
        self.id2.setObjectName("id2")
        self.rank2 = QtWidgets.QLabel(self.frame_2)
        self.rank2.setGeometry(QtCore.QRect(20, 0, 91, 51))
        self.rank2.setStyleSheet("font: 12pt \"Arial\";")
        self.rank2.setObjectName("rank2")
        self.name2 = QtWidgets.QLabel(self.frame_2)
        self.name2.setGeometry(QtCore.QRect(300, 0, 171, 51))
        self.name2.setStyleSheet("font: 12pt \"Arial\";")
        self.name2.setObjectName("name2")
        self.point2 = QtWidgets.QLabel(self.frame_2)
        self.point2.setGeometry(QtCore.QRect(490, 0, 131, 51))
        self.point2.setStyleSheet("font: 12pt \"Arial\";")
        self.point2.setObjectName("point2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(110, 280, 581, 61))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.id3 = QtWidgets.QLabel(self.frame_3)
        self.id3.setGeometry(QtCore.QRect(160, 0, 91, 51))
        self.id3.setStyleSheet("font: 12pt \"Arial\";")
        self.id3.setObjectName("id3")
        self.rank3 = QtWidgets.QLabel(self.frame_3)
        self.rank3.setGeometry(QtCore.QRect(20, 0, 91, 51))
        self.rank3.setStyleSheet("font: 12pt \"Arial\";")
        self.rank3.setObjectName("rank3")
        self.name3 = QtWidgets.QLabel(self.frame_3)
        self.name3.setGeometry(QtCore.QRect(300, 0, 171, 51))
        self.name3.setStyleSheet("font: 12pt \"Arial\";")
        self.name3.setObjectName("name3")
        self.point3 = QtWidgets.QLabel(self.frame_3)
        self.point3.setGeometry(QtCore.QRect(490, 0, 131, 51))
        self.point3.setStyleSheet("font: 12pt \"Arial\";")
        self.point3.setObjectName("point3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(110, 330, 581, 61))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.id4 = QtWidgets.QLabel(self.frame_4)
        self.id4.setGeometry(QtCore.QRect(160, 0, 91, 51))
        self.id4.setStyleSheet("font: 12pt \"Arial\";")
        self.id4.setObjectName("id4")
        self.rank4 = QtWidgets.QLabel(self.frame_4)
        self.rank4.setGeometry(QtCore.QRect(20, 0, 91, 51))
        self.rank4.setStyleSheet("font: 12pt \"Arial\";")
        self.rank4.setObjectName("rank4")
        self.name4 = QtWidgets.QLabel(self.frame_4)
        self.name4.setGeometry(QtCore.QRect(300, 0, 181, 51))
        self.name4.setStyleSheet("font: 12pt \"Arial\";")
        self.name4.setObjectName("name4")
        self.point4 = QtWidgets.QLabel(self.frame_4)
        self.point4.setGeometry(QtCore.QRect(490, 0, 131, 51))
        self.point4.setStyleSheet("font: 12pt \"Arial\";")
        self.point4.setObjectName("point4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.slot7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.id1.setText(_translate("MainWindow", "1"))
        self.rank1.setText(_translate("MainWindow", "1"))
        self.name1.setText(_translate("MainWindow", "1"))
        self.point1.setText(_translate("MainWindow", "1"))
        self.id2.setText(_translate("MainWindow", "1"))
        self.rank2.setText(_translate("MainWindow", "1"))
        self.name2.setText(_translate("MainWindow", "1"))
        self.point2.setText(_translate("MainWindow", "1"))
        self.id3.setText(_translate("MainWindow", "1"))
        self.rank3.setText(_translate("MainWindow", "1"))
        self.name3.setText(_translate("MainWindow", "1"))
        self.point3.setText(_translate("MainWindow", "1"))
        self.id4.setText(_translate("MainWindow", "1"))
        self.rank4.setText(_translate("MainWindow", "1"))
        self.name4.setText(_translate("MainWindow", "1"))
        self.point4.setText(_translate("MainWindow", "1"))
import background1_rc
