# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seven.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setFixedSize(1000, 825)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 825)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"border-image: url(:/beijing1/icons/2.png);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setStyleSheet("border-image: url(:/beijing1/icons/back.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.s4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s4.setGeometry(QtCore.QRect(500, 540, 71, 101))
        self.s4.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s4.setObjectName("s4")
        self.s5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s5.setGeometry(QtCore.QRect(580, 540, 71, 101))
        self.s5.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s5.setObjectName("s5")
        self.s6 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s6.setGeometry(QtCore.QRect(660, 540, 71, 101))
        self.s6.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s6.setObjectName("s6")
        self.s7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s7.setGeometry(QtCore.QRect(740, 540, 71, 101))
        self.s7.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s7.setObjectName("s7")
        self.s1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s1.setGeometry(QtCore.QRect(260, 540, 71, 101))
        self.s1.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s1.setObjectName("s1")
        self.s2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s2.setGeometry(QtCore.QRect(340, 540, 71, 101))
        self.s2.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s2.setObjectName("s2")
        self.s3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s3.setGeometry(QtCore.QRect(420, 540, 71, 101))
        self.s3.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s3.setObjectName("s3")
        self.s12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s12.setGeometry(QtCore.QRect(620, 660, 71, 101))
        self.s12.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s12.setObjectName("s12")
        self.s8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s8.setGeometry(QtCore.QRect(300, 660, 71, 101))
        self.s8.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s8.setObjectName("s8")
        self.s10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s10.setGeometry(QtCore.QRect(460, 660, 71, 101))
        self.s10.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s10.setObjectName("s10")
        self.s11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s11.setGeometry(QtCore.QRect(540, 660, 71, 101))
        self.s11.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s11.setObjectName("s11")
        self.s13 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s13.setGeometry(QtCore.QRect(700, 660, 71, 101))
        self.s13.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s13.setObjectName("s13")
        self.s9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.s9.setGeometry(QtCore.QRect(380, 660, 71, 101))
        self.s9.setStyleSheet("background-color: rgba(0, 0, 0,255);")
        self.s9.setObjectName("s9")
        self.b5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(660, 320, 71, 101))
        self.b5.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.b5.setObjectName("b5")
        self.b1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(340, 320, 71, 101))
        self.b1.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.b1.setObjectName("b1")
        self.b3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(500, 320, 71, 101))
        self.b3.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(580, 320, 71, 101))
        self.b4.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.b4.setObjectName("b4")
        self.b2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(420, 320, 71, 101))
        self.b2.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.b2.setObjectName("b2")
        self.m5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.m5.setGeometry(QtCore.QRect(660, 190, 71, 101))
        self.m5.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.m5.setObjectName("m5")
        self.m1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.m1.setGeometry(QtCore.QRect(340, 190, 71, 101))
        self.m1.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.m1.setObjectName("m1")
        self.m3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.m3.setGeometry(QtCore.QRect(500, 190, 71, 101))
        self.m3.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.m3.setObjectName("m3")
        self.m4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.m4.setGeometry(QtCore.QRect(580, 190, 71, 101))
        self.m4.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.m4.setObjectName("m4")
        self.m2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.m2.setGeometry(QtCore.QRect(420, 190, 71, 101))
        self.m2.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.m2.setObjectName("m2")
        self.f3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.f3.setGeometry(QtCore.QRect(580, 70, 71, 101))
        self.f3.setStyleSheet("background-color: rgba(0, 0, 0,0\n"
");")
        self.f3.setObjectName("f3")
        self.f2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.f2.setGeometry(QtCore.QRect(500, 70, 71, 101))
        self.f2.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.f2.setObjectName("f2")
        self.f1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.f1.setGeometry(QtCore.QRect(420, 70, 71, 101))
        self.f1.setStyleSheet("background-color: rgba(0, 0, 0,0\n"
");")
        self.f1.setObjectName("f1")
        self.front = QtWidgets.QLabel(self.centralwidget)
        self.front.setGeometry(QtCore.QRect(80, 90, 171, 81))
        self.front.setStyleSheet("color: rgb(0, 0, 255);\n"
"\n"
"font: 48pt \"隶书\";\n"
"")
        self.front.setObjectName("front")
        self.mid = QtWidgets.QLabel(self.centralwidget)
        self.mid.setGeometry(QtCore.QRect(80, 210, 171, 71))
        self.mid.setStyleSheet("color: rgb(255, 0, 127);\n"
"font: 48pt \"隶书\";\n"
"")
        self.mid.setObjectName("mid")
        self.back = QtWidgets.QLabel(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(80, 330, 171, 71))
        self.back.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 48pt \"隶书\";\n"
"")
        self.back.setObjectName("back")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 600, 161, 81))
        self.label_4.setStyleSheet("color: rgb(0, 0, 255);\n"
"color: rgb(170, 0, 0);\n"
"\n"
"font: 48pt \"隶书\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 10, 131, 41))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setStyleSheet("font: 14pt \"华文楷体\";\n"
"background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.slot11)
        self.pushButton_2.clicked.connect(MainWindow.find_game)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/beijing1/2.png\"/></p></body></html>"))
        self.front.setText(_translate("MainWindow", "前墩"))
        self.mid.setText(_translate("MainWindow", "中墩"))
        self.back.setText(_translate("MainWindow", "后墩"))
        self.label_4.setText(_translate("MainWindow", "手牌"))
        self.pushButton_2.setText(_translate("MainWindow", "寻找对局"))
import background1_rc
